package com.releevante.core.domain;

public enum TransactionItemStatusEnum {
  REPORTED_LOST,
  LOST,
  RETURNED,
  REPORTED_DAMAGE,
  DAMAGED,
  REPORTED_SOLD,
  SOLD,
  BORROWED,

  DOOR_OPENING,
  DOOR_OPENED,
  CHECKOUT_STARTED,
  CHECKOUT_PENDING,
  CHECKIN_STARTED,
  CHECKIN_PENDING,
  CHECKIN_SUCCESS,
  CHECKOUT_FAILED,
  CHECKOUT_SUCCESS
}
