package com.releevante.core.domain;

public enum TransactionItemStatusEnum {
  LOST,
  RETURNED,
  DAMAGED,
  SOLD,
  BORROWED,
  DOOR_OPENING,
  DOOR_OPENED,
  CHECKOUT_STARTED,
  CHECKOUT_PENDING,
  CHECKIN_STARTED,
  CHECKIN_PENDING,
  CHECKIN_SUCCESS,
  CHECKOUT_FAILED,
  CHECKOUT_SUCCESS
}
